# Generated by Django 2.2.4 on 2019-08-13 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190813_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(help_text='Action name', max_length=200),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Main E-Mail of the contributor', max_length=200),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Institution where the contributor belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Institution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Institution name', max_length=200),
        ),
    ]
